### ISSUE TITLE
The SPI delays are incorrectly read.

### ISSUE THREAD

**Issue by hdeveer** [Henneberg-Systemdesign/cp2130#21]
The function cp2130_read_channel_config() reads the pre/post and inter byte delays. Unfortunately the offset in the urb array are incorrect where the values are read.

This piece of code:
```
		chn->delay_mask = urb[1];
                chn->inter_byte_delay = urb[2] << 8;
		chn->inter_byte_delay |= urb[2] & 0xff;  // WRONG
		chn->post_assert_delay = urb[3] << 8;
		chn->post_assert_delay |= urb[4] & 0xff;
		chn->pre_deassert_delay = urb[5] << 8;
		chn->pre_deassert_delay |= urb[6] & 0xff; // <-- TO HERE
```
Should be:
```
		chn->delay_mask = urb[1];
                chn->inter_byte_delay = urb[2] << 8;
		chn->inter_byte_delay |= urb[3] & 0xff;
		chn->post_assert_delay = urb[4] << 8;
		chn->post_assert_delay |= urb[5] & 0xff;
		chn->pre_deassert_delay = urb[6] << 8;
		chn->pre_deassert_delay |= urb[7] & 0xff;
```

**Comment by dpfrey** [comment]
I noticed this yesterday as well!  👍  😄 

I have noticed that you have posted issues with solutions a couple of times.  Is there a reason why you're not submitting a pull request rather than including the solution in the issue?

**Comment by hdeveer** [comment]
Well no specific reason, I can fork the code and make a pull request. I did not create a stand-alone build environment yet to build the driver, so I'm not able to exactly verify the build.
I'm busy with a yocto build and patching a lot of code around to get everything to work.

And ofcourse I don't like very large pull requests because these are very hard to test/review.

And I want to leave it up to the owner to accept the changes or to comment on some solutions.
For this specific issue it is obvious thats is it wrong and what the solution is.

Ok I will push this one from my just created fork.

**Comment by hdeveer** [comment]
I tried to push the code (branch bugfix/issue-21) but I get a permission denied! I will try it via the fork.

**Comment by dpfrey** [comment]
Are you trying to push to your fork or to this repository? You likely don't have permission to push to this repository directly.

**Comment by dpfrey** [comment]
Also, once you push to your own fork, you can make a pull request from the web interface to your fork.

**Comment by hdeveer** [comment]
Just tried it but no way to create a pull request. If I push the "Create pull request" button I end up in the compare page of github. => Already found it out: I have to use the button of the forked repo itself. So actually it is a more of a PUSH requst. :-(

**Comment by dpfrey** [comment]
You're requesting that the maintainer pull from you.  I think that's where the name comes from.

**Comment by hdeveer** [comment]
Yeh I know. I always have trouble with all the git stuff: unlogical names for a bunch commands.
Anyhow the pull-request is now done.
Next time I create the issue via a pull request containing the complete bug description so we don't end up with 2 issues. Thanks for pointing it out.

**Comment by hdeveer** [comment]
See pull request #25.
