### ISSUE TITLE
USB transfer buffers must be DMA capable

### ISSUE THREAD

**Issue by dpfrey** [Henneberg-Systemdesign/cp2130#23]
See: https://www.spinics.net/lists/linux-usb/msg95593.html
Also the parameter documentation for the `transfer_buffer` member of `struct urb`:
```
 * @transfer_buffer:  This identifies the buffer to (or from) which the I/O
 *      request will be performed unless URB_NO_TRANSFER_DMA_MAP is set                                            
 *      (however, do not leave garbage in transfer_buffer even then).
 *      This buffer must be suitable for DMA; allocate it with         
 *      kmalloc() or equivalent.  For transfers to "in" endpoints, contents 
 *      of this buffer will be modified.  This buffer is used for the data
 *      stage of control transfers.
```

In the cp2130 driver, there are a bunch of different places that do `char urb[8];` or similar to allocate a buffer on the stack.  Instead it seems that we must kmalloc a buffer.  Also, I think it's misleading to name the variable `urb` or `ctrl_urb` because `struct urb` is a specific type in the kernel and what we are allocating is just the transfer buffer which gets set inside the `struct urb`.

**Comment by hdeveer** [comment]
I've seen that issue too. The patch looks good (only a very tiny remark). It is even more efficient because the buffer is only allocated once.
