### ISSUE TITLE
'urb' is not freed in in all cases.

### ISSUE THREAD

**Issue by hdeveer** [Henneberg-Systemdesign/cp2130#9]
In this function 'cp2130_spi_transfer_one_message()' there are a lot of "goto out" statements (all error cases). When such event happens the allocated 'urb' pointer is not freed.

**Comment by jh-hsd** [comment]
Ok, sorry. I should not do that during the weekend. Fixed it.

**Comment by hdeveer** [comment]
Solution looks perfect, fixed in commit: bf81ebd

**Comment by hdeveer** [comment]
Jochen,


May I contact you directly with questions about the cp2130 driver?

I have some remarks and questions and don't won't to pollute the github issue list with this.


Please respond to henri.de.veer@alten.nl

I'm located in the Netherlands.


regards,

Henri

________________________________
Van: Jochen Henneberg <notifications@github.com>
Verzonden: zondag 28 januari 2018 18:43:00
Aan: Henneberg-Systemdesign/cp2130
CC: Henri de Veer; Author
Onderwerp: Re: [Henneberg-Systemdesign/cp2130] 'urb' is not freed in in all cases. (#9)


Ok, sorry. I should not do that during the weekend. Fixed it.

**Comment by hdeveer** [comment]
Still one remark, looks a git issue: There is one change not visible in the history! The "err:" label has been replaced with "out:" and placed behind the kfree(urb) as it should be. Also the goto in the beginning of the function has been changed accordingly.
So the code is OK but you can't see it in the history, very strange :-(.

**Comment by dpfrey** [comment]
I would prefer that discussions/questions about the cp2130 driver happen in
public because I'm interested in seeing the discussion as well.
